# Generated by Django 4.1.13 on 2024-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainlogdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('trainname', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('logurl', models.TextField()),
                ('build', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['trainname', 'date'],
            },
        ),
    ]
