# Generated by Django 4.1.13 on 2024-07-17 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_allbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimalSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_error_msg', models.TextField(unique=True, verbose_name='Cleaned Error Message')),
                ('error_msg_signature', models.CharField(max_length=255, verbose_name='Error Message Signature')),
                ('err_sig_readable', models.CharField(max_length=255, verbose_name='Readable Error Message')),
                ('optimal_solution', models.TextField(verbose_name='Optimal Solutions')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date')),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
    ]
