# Generated by Django 4.1.13 on 2024-07-25 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_optimalsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=255, verbose_name='Error Message Signature')),
                ('readable_sig', models.CharField(max_length=255, verbose_name='Readable Error Message')),
                ('common_solution_flag', models.BooleanField(default=False, verbose_name='Applicable for this error signature')),
                ('common_solution', models.TextField(blank=True, null=True, verbose_name='Common Solutions')),
            ],
        ),
        migrations.RemoveField(
            model_name='optimalsolution',
            name='err_sig_readable',
        ),
        migrations.RemoveField(
            model_name='optimalsolution',
            name='error_msg_signature',
        ),
        migrations.AlterField(
            model_name='optimalsolution',
            name='optimal_solution',
            field=models.TextField(blank=True, null=True, verbose_name='Optimal Solutions'),
        ),
        migrations.AddField(
            model_name='optimalsolution',
            name='err_signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.errorsignature'),
            preserve_default=False,
        ),
    ]
