# Generated by Django 4.1.13 on 2024-07-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_errorsignature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorsignature',
            name='common_solution_flag',
            field=models.BooleanField(default=False, verbose_name='Given Common Solution Applicable to this Error sig'),
        ),
        migrations.AlterField(
            model_name='errorsignature',
            name='signature',
            field=models.CharField(max_length=255, unique=True, verbose_name='Error Message Signature'),
        ),
        migrations.AlterField(
            model_name='optimalsolution',
            name='err_signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.errorsignature'),
        ),
    ]
