# Generated by Django 4.1.13 on 2024-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_errorsignature_common_solution_flag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorsignature',
            options={'ordering': ['readable_sig']},
        ),
        migrations.AlterModelOptions(
            name='optimalsolution',
            options={'ordering': ['err_signature__readable_sig']},
        ),
        migrations.AddField(
            model_name='optimalsolution',
            name='email_address',
            field=models.EmailField(default='admin@cohesity.com', max_length=254),
        ),
        migrations.AddField(
            model_name='optimalsolution',
            name='err_category',
            field=models.CharField(choices=[('QA', 'QA'), ('INFRA', 'INFRA')], default='QA', max_length=10, verbose_name='Error'),
        ),
    ]
