# Generated by Django 4.1.13 on 2024-08-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_errorsignature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('Cohesity', 'cohesity'), ('HECP', 'hecp'), ('HEDP', 'hedp'), ('OnPrem', 'onprem')], max_length=255, verbose_name='Cohesity OS Type')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('train_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Train Name')),
                ('suite_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suite Group')),
                ('suite_owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suite Owner')),
                ('suite_squad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suite Squad')),
                ('suite_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suite name')),
            ],
        ),
        migrations.AlterField(
            model_name='optimalsolution',
            name='err_category',
            field=models.CharField(choices=[('QA', 'QA'), ('INFRA', 'INFRA')], default='QA', max_length=10, verbose_name='Error Category'),
        ),
    ]
