# Generated by Django 4.1.13 on 2024-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_squaddetails_alter_optimalsolution_err_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevereDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(null=True, verbose_name='Severe Error Message')),
                ('cleaned_error', models.CharField(max_length=255, verbose_name='Error Message Keywords')),
                ('error_category', models.CharField(choices=[('buggy', 'Buggy'), ('expected', 'Expected'), ('need_analysis', 'Need Analysis'), ('new_error', 'New Error')], max_length=255, verbose_name='Error Type')),
                ('bug_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bug ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments')),
            ],
        ),
        migrations.AlterField(
            model_name='squaddetails',
            name='os',
            field=models.CharField(choices=[('cohesity', 'Cohesity'), ('hecp', 'HECP'), ('hedp', 'HEDP'), ('onprem', 'OnPrem')], max_length=255, verbose_name='Cohesity OS Type'),
        ),
    ]
