# Generated by Django 4.1.13 on 2024-09-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_severedetail_alter_squaddetails_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severedetail',
            name='error_category',
            field=models.CharField(choices=[('buggy', 'Buggy'), ('expected', 'Expected'), ('need_analysis', 'Need Analysis'), ('new_error', 'New Error')], default='new_error', max_length=255, verbose_name='Error Type'),
        ),
    ]
