# Generated by Django 4.1.13 on 2024-10-23 20:31

from django.db import migrations, models
import django.db.models.deletion
import localapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteTag',
            fields=[
                ('id', models.CharField(default=localapp.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'db_table': 'localapp_suitetag',
            },
        ),
        migrations.CreateModel(
            name='TagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=255, verbose_name='Train Name')),
                ('suite_name', models.CharField(max_length=255, verbose_name='Suite Name')),
                ('tag_name', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='localapp.suitetag', verbose_name='Tag Name')),
            ],
        ),
    ]
