# Generated by Django 4.1.13 on 2024-10-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmapping',
            name='tag_name',
            field=models.ForeignKey(db_column='tag_name_id', on_delete=django.db.models.deletion.CASCADE, to='localapp.suitetag', verbose_name='Tag Name'),
        ),
    ]
