"""
Django settings for autotriage project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bwjd%s32yln+fmo09fk=%@14o=yrvk%h!@6d1c0$s2l)22t1i@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cron',
    'rest_framework',
    'autotriage',
    'restapi.apps.RestapiConfig',
    'localapp.apps.LocalappConfig'
]

# Set ENABLE_DJANGO_CRON=1 only if you still want reports.eng sync via django-cron.
ENABLE_DJANGO_CRON = os.getenv("ENABLE_DJANGO_CRON", "0").lower() in ("1", "true", "yes")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CRON_CLASSES = (
    [
        "autotriage.cronjob.PullCompletedSuites",
        "autotriage.cronjob.PullSquadDetails",
    ]
    if ENABLE_DJANGO_CRON
    else []
)

ROOT_URLCONF = 'autotriage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autotriage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'autotriage',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': '127.0.0.1',
            'port': 27017
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PLUTOURL = os.getenv("PLUTOURL")

PLUTOUSERNAME = os.getenv("PLUTOUSERNAME")

PLUTOPASSWORD = os.getenv("PLUTOPASSWORD")

os.environ["NLTK_DATA"]= os.path.join(BASE_DIR, "static", "libraries", "nltk_data")

# JSON-backed Mongo collections for dashboard dropdowns (set USE_MOCK_MONGO=1 when Mongo is down).
USE_MOCK_MONGO = os.getenv("USE_MOCK_MONGO", "0").lower() in ("1", "true", "yes")
MOCK_MONGO_DATA_DIR = os.getenv("MOCK_MONGO_DATA_DIR", str(BASE_DIR / "mock_data"))

# OpenAI-compatible endpoint (Ollama: http://127.0.0.1:11434/v1 , vLLM, etc.)
LLM_API_BASE = os.getenv("LLM_API_BASE", "").rstrip("/")
LLM_MODEL = os.getenv("LLM_MODEL", "")
LLM_API_KEY = os.getenv("LLM_API_KEY", "")

# Internal watchmen shares often use corporate TLS; set to 0 only if needed.
WATCHMEN_HTTP_VERIFY_SSL = os.getenv("WATCHMEN_HTTP_VERIFY_SSL", "1").lower() in ("1", "true", "yes")
